server:
  port: 8004
spring:
   servlet:
     multipart:
       maxFileSize: 10Mb
       maxRequestSize: 100Mb
   datasource:
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@10.7.25.230:1521:dcits
     username: CK_upright
     password: 111111
     hikari:
       maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
       maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
     tomcat:
       max-active: 20
       test-while-idle: true
       validation-query: select 1
       default-auto-commit: false
       min-idle: 15
       initial-size: 15
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
     mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp
     show-sql: true